# Generated by Django 5.2.1 on 2025-05-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="用户ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        default="defaultuser",
                        max_length=128,
                        unique=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default="defaultpassword", max_length=256, verbose_name="密码"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="temp@example.com",
                        max_length=254,
                        unique=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="00000000000",
                        max_length=11,
                        unique=True,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "head",
                    models.ImageField(
                        blank=True,
                        default="/media/images/光遇背景.jpg",
                        null=True,
                        upload_to="images",
                        verbose_name="头像",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        default="男",
                        max_length=32,
                        verbose_name="性别",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "ordering": ["created_time"],
            },
        ),
    ]
