# Generated by Django 5.2.1 on 2025-05-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_center",
            "0004_alter_user_managers_user_date_joined_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="个人简介"
            ),
        ),
    ]
