# Generated by Django 5.2.1 on 2025-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_center", "0005_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="手机号"
            ),
        ),
    ]
